### ISSUE TITLE
Bump solana-client

### ISSUE THREAD

**Issue by 0xBreath** [Ellipsis-Labs/phoenix-sdk#162]
Watch out for a PR. Trying to implement priority fees into SDKClient and it's on `solana-client = "1.10.32"`.
Tried to bump to `1.14.24` which has the `get_recent_prioritization_fees` endpoint in `solana_client::nonblocking::rpc_client::RpcClient` only to find out that `phoenix-seat-manager` is locked to `solana-client = "=1.14.9"`

You guys, this SDK is unusable on mainnet without priority fees. DO NOT ever lock versions. At the very least define a range, such as `solana-client = ">1.14,<1.15"`

I'm not the only one
https://github.com/Ellipsis-Labs/phoenix-seat-manager-v1/issues/7

**Comment by jarry-xiao** [comment]
I think it makes sense to lock the version on the program, but we can relax the version in a new crate. There is already a `phoenix-common` crate with relaxed constraint, and I can set up `phoenix-seat-manager-common` as well

**Comment by jarry-xiao** [comment]
Issue should be resolved in version 0.6.0
